import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home({ env }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify(env, null, 4)}</pre>
      </div>
    </div>
  );
}

export async function getStaticProps() {
  console.log("process.env from index.js");
  console.log(JSON.parse(JSON.stringify(process.env)));
  const env = JSON.parse(JSON.stringify(process.env));
  return {
    props: { env: env },
  };
}
